language: java
sudo: false
jdk:
- oraclejdk7
install: "./installViaTravis.sh"
script: "./buildViaTravis.sh"
cache:
  directories:
  - "$HOME/.gradle/caches/"
before_install:
- test $TRAVIS_PULL_REQUEST = false && openssl aes-256-cbc -K $encrypted_fe3705ff80a5_key -iv $encrypted_fe3705ff80a5_iv
  -in gradle.properties.enc -out ../../templates/gradle.properties -d || true
after_success:
- "./gradlew jacocoTestReport coveralls"
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/05d013f8ef7ec4b2bd17
    on_success: change
    on_failure: always
    on_start: never
