language: java
sudo: false
jdk:
- oraclejdk7
install: true
script: "./gradle/buildViaTravis.sh"
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_install:
- test $TRAVIS_PULL_REQUEST = false && openssl aes-256-cbc -K $encrypted_8a3d3d61e4fd_key -iv $encrypted_8a3d3d61e4fd_iv -in gradle.properties.enc -out gradle.properties -d || true
after_success:
- "./gradlew jacocoTestReport coveralls"
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/05d013f8ef7ec4b2bd17
    on_success: change
    on_failure: always
    on_start: never
