language: java
sudo: false
matrix:
  include:
    - jdk: openjdk8
      env: GRADLE_PUBLISH=true
    - jdk: openjdk11
      env: GRADLE_PUBLISH=false
install: true
script: "./gradle/buildViaTravis.sh"
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
after_success:
- "./gradlew jacocoTestReport coveralls"
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/05d013f8ef7ec4b2bd17
    on_success: change
    on_failure: always
    on_start: never
env:
  global:
  - secure: sVuIjLCVi1R9TvJOs2NqSQMGZUX+N/3Ip0meoHwmyVYe9wulJY5APUSurf+aKwegpDOPkk7WFSVAbysHih3v6mCCB+DtgkCxMKrRnGWzdLYe1plnpgXAHW4C3jZd8gag7IUvnAPMWrWb1GqfHEsWRoGclrNA5ie8R2pVLwKJX60=
  - secure: hln89z/ts2xvPBvF28s09pYu4nHn0CFyamOOXRFvHYffhylFUO0US1lZ3FVEMZWtXBwyrnAqv/6Mx/9dLOtl0mv8/qj65cWBSZIEGVoH/fs+IMETIcclZTBYb9iurBuwYR82Ptv4lcZ3bNZ1IJoeawP6TYjfnRn+RcsB1dlZYWI=
  - secure: dTk9rlgaWzJ5dpazYWPSKO3zrm5c6A1Epo4q2/WvdeyZ5jyPaVKJMyjN8VzhxQVH/AfdzXfdG3nPMal2qlijCXvxAhC5tpGim6mW29qKpYGx52TQ2WtM9iCSkckNEbfX+maWsd33Kf5w1ELCpIbWVFoe34ti84i2iCpsRII0PVI=
  - secure: hXoHvbvaYOtMe/bLYkcud/UrNjhT8M13KOWFfWwrvI6GhJxw6CVUFiYwHc0/HRwNN18vs73OZc5tFTtlMniiiEsZKY7voPQFXFRQY9fwEAbgWAO3CL3PireF6DwxaqNxrwfatxuuZ22NP89izLrv8hHAE68qiFZYL3WDHM/or3E=
  - secure: LcLoVTJAZYsiVdXjkZnSAGZJCGWD+hi+M+R7by6lAzBtLfuveEewaUoE2NlFvS/aLiO90NFIZa+7m89gKMljRWxTru1AA7EcAf0P+n8nw5VGg+02lZGQpLMY6AVW3uWyzgX1dWhV6zLNBSy2LnVpwu5HpocthltCblX/X1eODqo=
  - secure: Jt5x8YLjazRpRGG2roHvJevqo2+qYG+O1RkeBRMGX/MO7X3/9D4t/fO8uc8em5LIHriVDYCgB7XN0WKQgzKe93fzjtfE1tj2mMwGo5d3j/1IsQJZyHS8QYCh+C0IL/rXNtpfYdrHQvLN36srug03vytJaoElaE+y1iBErV10rWs=
